/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kwon37xi' at '14. 3. 31 오후 4:02' with Gradle 1.11
 *
 * @author kwon37xi, @date 14. 3. 31 오후 4:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
